name: Go Unit Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests with Coverage
        run: go test ./... -coverprofile=coverage.out

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4  # ✅ Updated from v3 to v4
        with:
          name: coverage-report
          path: coverage.out
